name: example
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  bubble: ^1.2.1
  flutter_svg: 2.0.3
  draggable_widget:
    path: ../
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_animate: ^4.2.0+1
  flutter_riverpod: ^2.1.3
  flutter_chat_bubble: ^2.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/icon/